const assert = require('node:assert/strict');
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
const root = path.resolve(__dirname, '../editor');
const server = http.createServer((req,res)=>{
  const file = path.resolve(root, '.' + (req.url === '/' ? '/index.html' : req.url.split('?')[0]));
  if(!file.startsWith(root + path.sep)){res.writeHead(403).end();return;}
  fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html','.css':'text/css','.png':'image/png'})[path.extname(file)]||'application/octet-stream');res.end(data);});
});
(async()=>{
  await new Promise(r=>server.listen(0,'127.0.0.1',r));
  const browser = await chromium.launch();
  let count=0;
  const ok=label=>{count++;console.log('PASS '+label);};
  try{
    const context=await browser.newContext({viewport:{width:1180,height:760},acceptDownloads:true});
    const page=await context.newPage(), errors=[];
    page.on('pageerror',e=>errors.push(e.message));
    await page.goto(`http://127.0.0.1:${server.address().port}`);
    await page.locator('#gearBtn').click();
    assert.equal(await page.locator('#themeBtn').inputValue(),'system');
    await page.emulateMedia({colorScheme:'dark'});
    await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');
    await page.emulateMedia({colorScheme:'light'});
    await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');
    await page.locator('#themeBtn').selectOption('dark');
    await page.emulateMedia({colorScheme:'light'});
    assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
    await page.locator('#themeBtn').selectOption('system');
    await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');
    await page.reload();
    assert.equal(await page.locator('#themeBtn').inputValue(),'system');
    ok('System appearance follows changes; explicit override and return to system persist');
    assert(await page.locator('#saveBtn').isDisabled());assert(await page.locator('#copyBtn').isDisabled());
    assert(await page.locator('#welcomeCapture').isVisible());ok('Empty state and disabled exports');
    await page.locator('#sampleLink').click();await page.waitForFunction(()=>!document.getElementById('saveBtn').disabled);
    assert.equal(await page.locator('[data-tab="style"]').getAttribute('aria-selected'),'true');ok('Image loading opens style inspector');
    await page.locator('#gearBtn').click();
    await page.locator('#themeBtn').selectOption('dark');assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
    await page.reload();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');ok('Appearance persists');
    await page.locator('#sampleLink').click();await page.waitForFunction(()=>!document.getElementById('saveBtn').disabled);
    const imagePoint=async(x,y)=>page.evaluate(({x,y})=>{const r=c.getBoundingClientRect();return {x:r.left+(state.pad+x)*r.width/c.width,y:r.top+(state.pad+barH()+y)*r.height/c.height};},{x,y});
    const clickImage=async(x,y)=>{const p=await imagePoint(x,y);await page.mouse.click(p.x,p.y);};
    await page.locator('[data-tab="pointer"]').click();await page.locator('[data-style="dark"]').click();
    await page.locator('#placeCursor').click();await clickImage(500,350);
    const pointerExport=await page.evaluate(()=>exportPng());
    await page.locator('#includeCursor').uncheck();const plainExport=await page.evaluate(()=>exportPng());
    assert.notEqual(pointerExport,plainExport);await page.locator('#includeCursor').check();
    assert.equal(await page.evaluate(()=>exportPng()),pointerExport);ok('Pointer is a reversible exported layer');
    await page.locator('#cursorHalo').check();assert.notEqual(await page.evaluate(()=>exportPng()),pointerExport);ok('Pointer highlight changes export');
    await page.locator('#includeCursor').uncheck();
    await page.locator('[data-tool="redact"]').click();
    let a=await imagePoint(100,100),b=await imagePoint(300,220);
    await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y);await page.mouse.up();
    const redacted=await page.evaluate(()=>exportPng());
    const pixel=await page.evaluate(async()=>{const i=new Image();i.src=exportPng();await i.decode();const t=document.createElement('canvas');t.width=i.width;t.height=i.height;const g=t.getContext('2d');g.drawImage(i,0,0);return [...g.getImageData(state.pad+200,state.pad+barH()+150,1,1).data];});
    assert.deepEqual(pixel,[21,23,27,255]);ok('Redaction exports opaque pixels');
    await page.evaluate(()=>{annots.push({type:'blur',x1:150,y1:110,x2:250,y2:210,width:4,color:'#fff'});render();});
    assert.deepEqual(await page.evaluate(()=>[...ctx.getImageData(state.pad+200,state.pad+barH()+150,1,1).data]),[21,23,27,255]);
    await page.evaluate(()=>{annots.pop();render();});ok('Blur cannot reveal an overlapping redaction');
    await page.getByRole('button',{name:'Undo',exact:true}).click();assert.equal(await page.evaluate(()=>exportPng()),plainExport);
    await page.getByRole('button',{name:'Redo',exact:true}).click();assert.equal(await page.evaluate(()=>exportPng()),redacted);ok('Undo/redo restores annotation exports');
    await page.locator('[data-tool="select"]').click();await clickImage(200,150);
    assert.equal(await page.evaluate(()=>exportPng()),redacted);ok('Selection handles are excluded from export');
    await page.locator('[data-tool="text"]').click();await clickImage(400,300);
    await page.locator('#textInput').fill('Keep this text');await page.locator('#textInput').press('Backspace');
    assert(await page.locator('#textInput').isVisible());await page.locator('#textInput').press('Enter');
    assert.equal(await page.evaluate(()=>annots.at(-1).text),'Keep this tex');ok('Text input owns editing keys');
    const downloadPromise=page.waitForEvent('download');await page.locator('#saveBtn').click();const download=await downloadPromise;
    assert(download.suggestedFilename().endsWith('.png'));assert.equal(await download.failure(),null);ok('PNG download');
    for(const size of [{width:760,height:520},{width:1180,height:760},{width:1920,height:1080}]){
      await page.setViewportSize(size);assert(await page.locator('#saveBtn').isVisible());
      assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    }ok('Minimum and large window layouts');
    assert.deepEqual(errors,[]);ok('No browser runtime errors');
    await context.close();

    const native=await browser.newContext({viewport:{width:1180,height:760}});
    await native.addInitScript(()=>{
      window.hostMessages=[];let receive;
      window.chrome=window.chrome||{};
      window.chrome.webview={postMessage:m=>window.hostMessages.push(m),addEventListener:(_,cb)=>receive=cb};
      window.deliver=m=>receive({data:m});
    });
    const app=await native.newPage();app.on('pageerror',e=>errors.push(e.message));
    await app.goto(`http://127.0.0.1:${server.address().port}`);
    assert(await app.evaluate(()=>hostMessages.some(m=>m.type==='ready')));
    await app.evaluate(()=>deliver({type:'windowState',maximized:true}));
    assert(await app.locator('.restore-icon').isVisible());
    assert.equal(await app.locator('[data-w=max]').getAttribute('aria-label'),'Restore');
    await app.locator('[data-w=max]').click();
    assert(await app.evaluate(()=>hostMessages.some(m=>m.type==='max')));
    await app.evaluate(()=>deliver({type:'windowState',maximized:false}));
    assert(await app.locator('.maximize-icon').isVisible());
    assert(!(await app.locator('.restore-icon').isVisible()));
    for(const action of ['min','close']){
      await app.locator('[data-w='+action+']').click();
      assert(await app.evaluate(action=>hostMessages.some(m=>m.type===action),action));
    }
    ok('Window controls send actions and reflect maximize/restore state');
    await app.evaluate(()=>deliver({type:'settings',value:{autoCopy:false,hotkey:'ctrl+shift+4',captureDelay:3,includeCursor:false,autoUpdate:false}}));
    assert.equal(await app.locator('#captureDelay').inputValue(),'3');
    await app.locator('#captureBtn').click();assert(await app.evaluate(()=>hostMessages.some(m=>m.type==='capture'&&m.mode==='Region')));ok('Native settings and capture bridge');
    await app.locator('#gearBtn').click();
    assert(!(await app.locator('#clearFolder').isVisible()));
    assert.match(await app.locator('#saveLocationHelp').textContent(),/opens a dialog/);
    await app.locator('#chooseFolder').click();
    assert(await app.evaluate(()=>hostMessages.some(m=>m.type==='chooseSaveFolder')));
    await app.evaluate(()=>deliver({type:'settings',value:{saveFolder:'C:\\Screenshots'}}));
    assert(await app.locator('#clearFolder').isVisible());
    assert.match(await app.locator('#saveLocationHelp').textContent(),/directly to this folder/);
    await app.locator('#clearFolder').click();
    assert(await app.evaluate(()=>hostMessages.some(m=>m.type==='clearSaveFolder')));
    await app.evaluate(()=>deliver({type:'settings',value:{saveFolder:''}}));
    assert(!(await app.locator('#clearFolder').isVisible()));
    ok('Save location explains current mode and only offers reset for a configured folder');
    await app.evaluate(()=>deliver({type:'update',state:'downloading',progress:42,message:'Downloading…',version:'0.2.0'}));
    assert(await app.locator('#checkUpdate').isDisabled());assert.equal(await app.locator('#updateProgress').getAttribute('value'),'42');
    await app.evaluate(()=>deliver({type:'update',state:'ready',progress:100,message:'Ready to restart',version:'0.2.0'}));
    assert(await app.locator('#installUpdate').isVisible());await app.locator('#installUpdate').click();
    assert(await app.evaluate(()=>hostMessages.some(m=>m.type==='installUpdate')));
    await app.evaluate(()=>deliver({type:'update',state:'error',progress:0,message:'Try again',version:'0.2.0'}));
    assert(!(await app.locator('#checkUpdate').isDisabled()));assert(!(await app.locator('#installUpdate').isVisible()));ok('Update progress, explicit restart, and retry states');
    await app.evaluate(()=>deliver({type:'image',data:makeSample(),cursor:{x:450,y:300,hotX:2,hotY:3,width:6,height:6,data:(()=>{const c=document.createElement('canvas');c.width=c.height=6;const x=c.getContext('2d');x.fillStyle='#ff0000';x.fillRect(0,0,6,6);return c.toDataURL();})()}}));
    await app.waitForFunction(()=>hostMessages.some(m=>m.type==='hasImage'));
    assert(!(await app.locator('#saveBtn').isDisabled()));ok('Native image and cursor delivery');
    await app.locator('[data-tab="pointer"]').click();await app.locator('#includeCursor').check();await app.locator('[data-style="native"]').click();
    assert.deepEqual(await app.evaluate(()=>[...ctx.getImageData(state.pad+449,state.pad+barH()+298,1,1).data]),[255,0,0,255]);
    await app.locator('#includeCursor').uncheck();
    assert.notDeepEqual(await app.evaluate(()=>[...ctx.getImageData(state.pad+449,state.pad+barH()+298,1,1).data]),[255,0,0,255]);
    await app.locator('[data-tab="style"]').click();ok('Native cursor rendering respects hotspot and visibility');
    await app.locator('#copyBtn').click();
    let request=await app.evaluate(()=>hostMessages.filter(m=>m.type==='copy').at(-1));
    await app.evaluate(id=>deliver({type:'exportResult',requestId:id,success:true}),request.requestId);
    assert.equal(await app.evaluate(()=>hostMessages.filter(m=>m.type==='documentState').at(-1).dirty),false);
    await app.locator('#pad').fill('80');await app.locator('#pad').dispatchEvent('input');
    assert.equal(await app.evaluate(()=>hostMessages.filter(m=>m.type==='documentState').at(-1).dirty),true);
    await app.locator('#saveBtn').click();request=await app.evaluate(()=>hostMessages.filter(m=>m.type==='save').at(-1));
    await app.evaluate(id=>deliver({type:'exportResult',requestId:id,success:false}),request.requestId);
    assert.equal(await app.evaluate(()=>hostMessages.filter(m=>m.type==='documentState').at(-1).dirty),true);
    await app.locator('#saveBtn').click();request=await app.evaluate(()=>hostMessages.filter(m=>m.type==='save').at(-1));
    await app.locator('#pad').fill('90');await app.locator('#pad').dispatchEvent('input');
    await app.evaluate(id=>deliver({type:'exportResult',requestId:id,success:true}),request.requestId);
    assert.equal(await app.evaluate(()=>hostMessages.filter(m=>m.type==='documentState').at(-1).dirty),true);
    ok('Export acknowledgement preserves unsaved changes, including edits during export');

    assert.deepEqual(errors,[]);
    console.log(`\n${count} checks passed.`);
  }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
